### ISSUE TITLE
Pcapng doesn't work in v1.0.9

### ISSUE THREAD

**Issue by LtRipley36706** [tfarley/aclogview#11]
Some pcapng files seem to be loading in blank but appear to be valid pcaps, they worked previously in v1.0.8

Please take a look at the attached pcap and see if anything jumps out at you that would solve this issue

[DesertMine.zip](https://github.com/tfarley/aclogview/files/966353/DesertMine.zip)

**Comment by tfarley** [comment]
Thanks for the heads up and the example. Pushed a fix for this in 1.0.10 - let me know if that works and if you run into any other issues.

**Comment by LtRipley36706** [comment]
I'd like to send you a 350mb zip file with a bunch of PCAPS that I've found that don't decode or decode well, wondering if they're salvageable or a lost cause...
